<?php

namespace FedexRest\Services\Ship\Type;

class LabelStockType
{
    const _PAPER_4X6 = 'PAPER_4X6';
    const _PAPER_4X675 = 'PAPER_4X675';
    const _PAPER_4X8 = 'PAPER_4X8';
    const _PAPER_4X9 = 'PAPER_4X9';
    const _PAPER_7X475 = 'PAPER_7X475';
    const _PAPER_85X11_BOTTOM_HALF_LABEL = 'PAPER_85X11_BOTTOM_HALF_LABEL';
    const _PAPER_85X11_TOP_HALF_LABEL = 'PAPER_85X11_TOP_HALF_LABEL';
    const _PAPER_LETTER = 'PAPER_LETTER';
    const _STOCK_4X675_LEADING_DOC_TAB = 'STOCK_4X675_LEADING_DOC_TAB';
    const _STOCK_4X8 = 'STOCK_4X8';
    const _STOCK_4X9_LEADING_DOC_TAB = 'STOCK_4X9_LEADING_DOC_TAB';
    const _STOCK_4X6 = 'STOCK_4X6';
    const _STOCK_4X675_TRAILING_DOC_TAB = 'STOCK_4X675_TRAILING_DOC_TAB';
    const _STOCK_4X9_TRAILING_DOC_TAB = 'STOCK_4X9_TRAILING_DOC_TAB';
    const _STOCK_4X675 = 'STOCK_4X675';
    const _STOCK_4X9 = 'STOCK_4X9';
}
