<?php declare(strict_types=1);

namespace FedexRest\Tests\TrackService;

use FedexRest\Authorization\Authorize;
use FedexRest\Exceptions\MissingAccessTokenException;
use FedexRest\Exceptions\MissingTrackingNumberException;
use FedexRest\Services\Track\TrackByTrackingNumberRequest;
use PHPUnit\Framework\TestCase;

class TrackByTrackingNumberRequestTest extends TestCase
{
    protected Authorize $auth;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->auth = (new Authorize)
            ->setClientId('l76ac1844c563048e582a791871f51f1f5')
            ->setClientSecret('f4ae9fc64c694b14af5ef3716a902a1b');
    }

    public function testSetApiEndpoint()
    {
        $request = new TrackByTrackingNumberRequest();

        $this->assertObjectHasAttribute('api_endpoint', $request);
        $this->assertEquals('/track/v1/trackingnumbers', $request->api_endpoint);
    }


    public function testProductionMode()
    {
        $request = (new TrackByTrackingNumberRequest())->useProduction();
        $this->assertObjectHasAttribute('production_mode', $request);
        $this->assertEquals(true, $request->production_mode);
        $this->assertEquals('https://apis.fedex.com', $request->getApiUri());
    }

    public function testMissingAuthCredentials()
    {

        try {
            (new TrackByTrackingNumberRequest())
                ->setTrackingNumber('020207021381215')
                ->request();
        } catch (MissingAccessTokenException $e) {
            $this->assertEquals('Authorization token is missing. Make sure it is included', $e->getMessage());
        }

    }

    public function testRawResponse()
    {
        $response = (new TrackByTrackingNumberRequest())
            ->asRaw()
            ->setTrackingNumber('020207021381215')
            ->setAccessToken($this->auth->authorize()->access_token)->request();

        $this->assertObjectHasAttribute('headers', $response);
    }

    public function testMissingTrackingNumber()
    {

        try {
            (new TrackByTrackingNumberRequest())
                ->setAccessToken($this->auth->authorize()->access_token)->request();
        } catch (MissingTrackingNumberException $e) {
            $this->assertEquals('Please enter at least one tracking number', $e->getMessage());
        }

    }

    public function testResponseSuccess()
    {
        $response = (new TrackByTrackingNumberRequest())
            ->setTrackingNumber('020207021381215')
            ->setAccessToken($this->auth->authorize()->access_token)->request();

        $this->assertObjectHasAttribute('transactionId', $response);
    }
}
